### ISSUE TITLE
Caching doesn't seem to work

### ISSUE THREAD

**Issue by Nilzor** [Schibsted-Tech-Polska/good-guy-http#4]
...or I don't understand how to use it. Based on the documentation I'd expect that by setting `forceCaching: { cached: true, timeToLive: 5000}`, all requests would be cached in-memory by the library. This does not happen. See code below:

```
var goodGuy = require('good-guy-http');

var options = {
    method: 'GET',
    maxRetries: 3,
    timeout: 5000,
    defaultCaching: {
        cached: true,
        timeToLive: 5000,
        mustRevalidate: false
    },
    forceCaching: {
        cached: true,
        timeToLive: 5000,
        mustRevalidate: false
    },
    headers: {
        'user-agent': 'first',
        'accept': 'application/json, text/html'
    }
};


goodGuy(options)('http://httpbin.org/user-agent').then((res1) => {
    options.headers['user-agent'] = 'second';
    goodGuy(options)('http://httpbin.org/user-agent').then((res2) => {
        console.log("Res1: " + res1.body + ", Res2: " + res2.body);
        if (res2.body.indexOf("second") !== -1) {
            console.error("Expected cached response to be returned!");
        }
    });
}, err => {
    console.error(err);
});
```

This produces output: 

```
Res1: {
  "user-agent": "first"
}
, Res2: {
  "user-agent": "second"
}
Expected cached response to be returned!
```

Am I misunderstanding something fundamental, or is caching simply not working?

**Comment by krzychukula** [comment]
I had opposite problem not so long ago so it should work imho. Have you tried naming the result of goodGuy(options)? Maybe cache is associated with one instance?

```

var request = goodGuy(http);

request('http://httpbin.org/user-agent').then((res1) => {
    options.headers['user-agent'] = 'second';
    request('http://httpbin.org/user-agent').then((res2) => {
        console.log("Res1: " + res1.body + ", Res2: " + res2.body);
        if (res2.body.indexOf("second") !== -1) {
            console.error("Expected cached response to be returned!");
        }
    });
}, err => {
    console.error(err);
});
```

It will probably help to find a problem or to improve documentation if you can check it :)

**Comment by Nilzor** [comment]
That was it! :+1: 

I'll refactor my code to only have one global instance then.

**Comment by jakubwasilewski** [comment]
Indeed, that's the case - unless you specify a cache yourself (using the `cache` option), each time you instantiate good-guy-http, a new cache instance will be created. Which is not what you want :). 

I'll have to think about it - maybe the way it is implemented now is counterintuitive, since the implicit cache behaves differently from when you explicitly specify it? For what it's worth, the expected way to use the library is to use one globally configured instance - mostly so you don't have to keep setting the same options and have the configuration in one place.

@krzychukula - thanks for helping. Closing for now, as there is no actual bug - I'll keep the topic in mind for the next release, though.
